/// Egyptian universities list used for strict selection in registration flows.
const List<String> egyptianUniversities = [
  'Ain Shams University',
  'Alexandria University',
  'Al-Azhar University',
  'Aswan University',
  'Assiut University',
  'Beni-Suef University',
  'Benha University',
  'Cairo University',
  'Damietta University',
  'Damanhour University',
  'Fayoum University',
  'Helwan University',
  'Kafrelsheikh University',
  'Luxor University',
  'Mansoura University',
  'Minia University',
  'New Valley University',
  'Port Said University',
  'Sohag University',
  'South Valley University',
  'Suez Canal University',
  'Suez University',
  'Tanta University',
  'BUE',
  'AUC',
  'Zagazig University',
  'October 6 University',
  'GUC',
  'GIU',
  'MSA',
  'EUE',
  'Coventry',
  'FUE',
  'UH',
  'UPEI',
  'AAST',
];
