// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEmYc4rOoArsDapIH2z5fvF-MvNFJ-y4',
    appId: '1:347635239568:web:b2e9e513f77c6dfc40a615',
    messagingSenderId: '347635239568',
    projectId: 'fir-8bdb4',
    authDomain: 'fir-8bdb4.firebaseapp.com',
    storageBucket: 'fir-8bdb4.firebasestorage.app',
    measurementId: 'G-L63NJBTTTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbHAonceVDlA929J6NJ69z8sbA5joFOw',
    appId: '1:347635239568:android:c7bee8cef73c5c9f40a615',
    messagingSenderId: '347635239568',
    projectId: 'fir-8bdb4',
    storageBucket: 'fir-8bdb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9jtcKpZu5-JzYRpSqGkRerF_OEaFr49w',
    appId: '1:347635239568:ios:912458ab2deac24540a615',
    messagingSenderId: '347635239568',
    projectId: 'fir-8bdb4',
    storageBucket: 'fir-8bdb4.firebasestorage.app',
    iosClientId: '347635239568-38gpsi90hsirdpdn8eg2bptmvtiamklp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9jtcKpZu5-JzYRpSqGkRerF_OEaFr49w',
    appId: '1:347635239568:ios:912458ab2deac24540a615',
    messagingSenderId: '347635239568',
    projectId: 'fir-8bdb4',
    storageBucket: 'fir-8bdb4.firebasestorage.app',
    iosClientId: '347635239568-38gpsi90hsirdpdn8eg2bptmvtiamklp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXEmYc4rOoArsDapIH2z5fvF-MvNFJ-y4',
    appId: '1:347635239568:web:7cfd55d6f3c08acc40a615',
    messagingSenderId: '347635239568',
    projectId: 'fir-8bdb4',
    authDomain: 'fir-8bdb4.firebaseapp.com',
    storageBucket: 'fir-8bdb4.firebasestorage.app',
    measurementId: 'G-J4EG9FTC9N',
  );
}
